# producer configuration file h1
---
  filePath: use-cases/varying-networking-conditions/varying-link-latency/word-count/dataDir/randomText2.txt
  topicName: inTopic
  totalMessages: 1
  producerInstances: 1
...